pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        PACKER_FILE = "jenkins_slave_ami.pkr.hcl"
    }

    stages {
        stage ('Checkout code') {
            steps {
                git branch: 'main', url: 'https://github.com/Barney7777/petclinic_IaC_K8sManifests.git'
            }
        }

        stage ('packer init') {
            steps {
                dir("Packer-AMI/AMI-Jenkins-slave-node") {
                    script {
                        echo "Initializing Packer"
                        sh "packer init $PACKER_FILE"
                    }
                }
            }
        }

        stage ('packer fmt') {
            steps {
                dir("Packer-AMI/AMI-Jenkins-slave-node") {
                    script {
                        echo "formatting Packer"
                        sh "packer fmt $PACKER_FILE"
                    }
                }
            }
        }

        stage ('packer validate') {
            steps {
                dir("Packer-AMI/AMI-Jenkins-slave-node") {
                    script {
                        echo "validating Packer"
                        sh "packer validate $PACKER_FILE"
                    }
                }
            }
        }

        stage ('packer build ami') {
            steps {
                dir("Packer-AMI/AMI-Jenkins-slave-node") {
                    script {
                        echo "Building Packer"
                        sh "packer build $PACKER_FILE"
                    }
                }
            }
        }
    }
}