name: Jenkins Server Provision with Terraform

on:
  push:
    branches:
      - main
      - devops-barney
    paths:
      - Packer-AMI/Jenkins-Server/**
  pull_request:
    branches:
      - main
      - devops-barney
    paths:
      - Packer-AMI/Jenkins-Server/**
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      approve_destroy:
        description: 'Approve destroy action'
        required: false
        type: boolean

env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   AWS_REGION: ap-southeast-2

jobs:
  apply:
    name: "Provision Jenkins server via TF"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Packer-AMI/Jenkins-Server
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -out planfile
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false planfile
  
  destroy:
    name: "Destroy Jenkins server via TF"
    runs-on: ubuntu-latest
    needs: apply
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    defaults: 
      run:
        shell: bash
        working-directory: ./Packer-AMI/Jenkins-Server
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Request Approval
        uses: actions/approval@v1
        if: github.event.inputs.approve_destroy != 'true'
        with:
        body: 'This action will destroy the infrastructure. Are you sure you want to proceed?'
        title: 'Approve Infrastructure Destruction'

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        
